--  Shell_Sort — Ada 2023 educational package for classic Shellsort
--  (Shell's method, 1959) on Integer arrays with a bounded length.
--  In-place diminishing-gap insertion sort. Gap sequence: Marcin Ciura
--  (1, 4, 10, 23, 57, 132, 301, 701), extended for n > 701 by successive
--  floor(2.25 · h) / descending floor(h / 2.25). Not stable in general.
--  Reference: https://en.wikipedia.org/wiki/Shellsort

pragma Ada_2022;

package Shell_Sort
  with SPARK_Mode => Off
is

   ---------------------------------------------------------------------------
   -- Capacity bounds (educational; raise Invalid_Argument on overflow)
   ---------------------------------------------------------------------------

   --  Maximum array length accepted by Sort.
   --  Shellsort is typically subquadratic for good gap sequences, so a
   --  large educational bound is fine. The sort is in-place (O(1) aux).
   Max_N : constant Positive := 100_000;

   ---------------------------------------------------------------------------
   -- Domain
   ---------------------------------------------------------------------------

   type Element_Array is array (Natural range <>) of Integer;

   Invalid_Argument : exception;
   --  Raised when A'Length > Max_N.

   ---------------------------------------------------------------------------
   -- Algorithm sketch (classic Shellsort / Wikipedia)
   ---------------------------------------------------------------------------
   --  Shellsort generalizes insertion sort: for each gap h in a decreasing
   --  sequence that ends with 1, perform insertion sort on each of the
   --  h interleaved subsequences A(i), A(i+h), A(i+2h), … (h-sorting).
   --  After the final h = 1 pass the array is fully sorted.
   --
   --  Gap sequence used here (documented in README):
   --    * Published Ciura gaps, descending, for every h < n:
   --        701, 301, 132, 57, 23, 10, 4, 1
   --    * When n > 701, larger gaps are generated by extending Ciura with
   --        h_k = floor(2.25 · h_{k-1})
   --      and consumed descending via
   --        h := floor(h / 2.25)
   --      until the published sequence takes over.
   --
   --  Not stable: gapped insertions can move equal keys past one another.
   --  Adaptive: partially sorted input leaves less work for small gaps.
   --  Do not `with` sibling Ada-* packages.

   ---------------------------------------------------------------------------
   -- Sorting
   ---------------------------------------------------------------------------

   procedure Sort (A : in out Element_Array);
   --  Ascending classic Shellsort (Ciura gaps + 2.25 extension).
   --  Empty and singleton arrays are no-ops.
   --  Raises Invalid_Argument when A'Length > Max_N.

   function Is_Sorted (A : Element_Array) return Boolean;
   --  True iff A is nondecreasing (ascending) in index order.
   --  Empty and singleton arrays are considered sorted.

end Shell_Sort;
